import 'package:car_sale_app/app_values/app_images.dart';
import 'package:car_sale_app/model/Car.dart';
import 'package:car_sale_app/model/Equipment.dart';
import 'package:car_sale_app/model/maintenance_costs.dart';

abstract class AudiModel {
  static Car audiA3Blue = Car(
    id: '2',
    brand: 'Audi',
    model: 'A3',
    image: AppImages.audiA3Blue,
    price: 4668303,
    bodyColor: 'Синий',
    productionYear: 2021,
    bodyType: 'Седан',
    transmission: 'АКПП',
    engineType: 'Бензиновый',
    engineVolume: 1.4,
    equipment: Equipment(
      id: '2',
      title: 'Sedan 35 TFSI tiptronic',
      seatUpholstery: 'Marathon',
      heatedSeats: 'Подогрев передних сидений',
      airbags: '6 подушек',
      onBoardComputer: 'Маршрутный компьютер',
      horsePower: 150,
      maxTorque: 250,
      typeOfFuel: 'Бензиновый',
      accelerationTime: 8.2,
      maxSpeed: 224,
      airConditioningSystem: 'Климат контроль',
      multifunctionSteeringWheel:
          'Многофункциональный кожаный руль с функция пере',
      fuelTankVolume: 50,
      centralLocking:
          'Центральный замок с дистанционным управлением без функции Safelock',
      trunkVolume: '425',
      driveUnit: 'Передний',
      additionalOptions: [
        'Адаптация для стран с холодным климатом',
        'Камера заднего вида',
        'Система Эра-Глонасс',
      ],
    ),
    maintenanceCosts: MaintenanceCosts(
      id: '2',
      typeOfFuel: 'аи-95',
      fuelConsumptionUrbanCycle: 5.9,
      extraUrbanFuelConsumption: 4.1,
      combinedFuelConsumption: 4.8,
      travelDistance: 510,
      horsePower: 150,
      price: 4668303,
    ),
  );

  static Car audiA3White = Car(
    id: '2',
    brand: 'Audi',
    model: 'A3',
    image: AppImages.audiA3White,
    price: 4658168,
    bodyColor: 'Белый',
    productionYear: 2021,
    bodyType: 'Седан',
    transmission: 'АКПП',
    engineType: 'Бензиновый',
    engineVolume: 1.4,
    equipment: Equipment(
      id: '2',
      title: 'Sedan 35 TFSI tiptronic',
      seatUpholstery: 'Marathon',
      heatedSeats: 'Подогрев передних сидений',
      airbags: '6 подушек',
      onBoardComputer: 'Маршрутный компьютер',
      horsePower: 150,
      maxTorque: 250,
      typeOfFuel: 'Бензиновый',
      accelerationTime: 8.2,
      maxSpeed: 224,
      airConditioningSystem: 'Климат контроль',
      multifunctionSteeringWheel:
          'Многофункциональный кожаный руль с функция пере',
      fuelTankVolume: 50,
      centralLocking:
          'Центральный замок с дистанционным управлением без функции Safelock',
      trunkVolume: '425',
      driveUnit: 'Передний',
      additionalOptions: [
        'Адаптация для стран с холодным климатом',
        'Камера заднего вида',
        'Система Эра-Глонасс',
      ],
    ),
    maintenanceCosts: MaintenanceCosts(
      id: '2',
      typeOfFuel: 'аи-95',
      fuelConsumptionUrbanCycle: 5.9,
      extraUrbanFuelConsumption: 4.1,
      combinedFuelConsumption: 4.8,
      travelDistance: 510,
      horsePower: 150,
      price: 4658168,
    ),
  );

  static Car audiA3Black = Car(
    id: '2',
    brand: 'Audi',
    model: 'A3',
    image: AppImages.audiA3Black,
    price: 5466654,
    bodyColor: 'Черный',
    productionYear: 2022,
    bodyType: 'Седан',
    transmission: 'АКПП',
    engineType: 'Бензиновый',
    engineVolume: 1.4,
    equipment: Equipment(
      id: '2',
      title: 'Sedan 35 TFSI tiptronic',
      seatUpholstery: 'Marathon',
      heatedSeats: 'Подогрев передних сидений',
      airbags: '6 подушек',
      onBoardComputer: 'Маршрутный компьютер',
      horsePower: 150,
      maxTorque: 250,
      typeOfFuel: 'Бензиновый',
      accelerationTime: 8.2,
      maxSpeed: 224,
      airConditioningSystem: 'Климат контроль',
      multifunctionSteeringWheel:
          'Многофункциональный кожаный руль с функция пере',
      fuelTankVolume: 50,
      centralLocking:
          'Центральный замок с дистанционным управлением без функции Safelock',
      trunkVolume: '425',
      driveUnit: 'Передний',
      additionalOptions: [
        'Адаптация для стран с холодным климатом',
        'Камера заднего вида',
        'Система Эра-Глонасс',
      ],
    ),
    maintenanceCosts: MaintenanceCosts(
      id: '2',
      typeOfFuel: 'аи-95',
      fuelConsumptionUrbanCycle: 5.9,
      extraUrbanFuelConsumption: 4.1,
      combinedFuelConsumption: 4.8,
      travelDistance: 510,
      horsePower: 150,
      price: 5466654,
    ),
  );
}
