import 'package:car_sale_app/app_values/app_images.dart';
import 'package:car_sale_app/model/Car.dart';
import 'package:car_sale_app/model/Equipment.dart';
import 'package:car_sale_app/model/maintenance_costs.dart';

abstract class MazdaData {
  static Car mazdaCx5Grey = Car(
    id: '1',
    brand: 'Mazda',
    model: 'Cx-5',
    image: AppImages.mazdaCx5Grey,
    price: 3202964,
    bodyColor: 'Серый',
    productionYear: 2022,
    bodyType: 'Кроссовер',
    transmission: 'АКПП',
    engineType: 'Бензиновый',
    engineVolume: 2.0,
    equipment: Equipment(
      id: '1',
      title: 'DRIVE 2WD',
      seatUpholstery: 'Alcantara',
      heatedSeats: 'Подогрев передних сидений',
      airbags: '7 подушек',
      onBoardComputer: 'Маршрутный компьютер',
      horsePower: 149,
      maxTorque: 208,
      typeOfFuel: 'Бензиновый',
      accelerationTime: 10.3,
      maxSpeed: 200,
      airConditioningSystem: 'Климат контроль (2 зоны)',
      multifunctionSteeringWheel: 'Управление аудиосистемой на рулевом колесе',
      fuelTankVolume: 58,
      centralLocking: 'Центральный замок с дистанционным управлением',
      trunkVolume: '442',
      driveUnit: 'Передний',
      additionalOptions: [
        'Автоматическая блокировка дверных замков при начале движения',
        'Электронный стояночный тормоз',
        'Система Эра-Глонасс',
      ],
    ),
    maintenanceCosts: MaintenanceCosts(
        id: '1',
        typeOfFuel: 'аи-95',
        fuelConsumptionUrbanCycle: 8.9,
        extraUrbanFuelConsumption: 6.2,
        combinedFuelConsumption: 7.2,
        travelDistance: 590,
        horsePower: 149,
        price: 3202964),
  );

  static Car mazdaCx5Red = Car(
    id: '1',
    brand: 'Mazda',
    model: 'Cx-5',
    image: AppImages.mazdaCx5Red,
    price: 3102964,
    bodyColor: 'Красный',
    productionYear: 2022,
    bodyType: 'Кроссовер',
    transmission: 'АКПП',
    engineType: 'Бензиновый',
    engineVolume: 2.0,
    equipment: Equipment(
      id: '1',
      title: 'ACTIVE 2WD/4WD',
      seatUpholstery: 'Alcantara',
      heatedSeats: 'Подогрев передних сидений',
      airbags: '7 подушек',
      onBoardComputer: 'Маршрутный компьютер',
      horsePower: 149,
      maxTorque: 208,
      typeOfFuel: 'Бензиновый',
      accelerationTime: 10.3,
      maxSpeed: 200,
      airConditioningSystem: 'Климат контроль (2 зоны)',
      multifunctionSteeringWheel: 'Управление аудиосистемой на рулевом колесе',
      fuelTankVolume: 58,
      centralLocking: 'Центральный замок с дистанционным управлением',
      trunkVolume: '442',
      driveUnit: 'Передний',
      additionalOptions: [
        'Автоматическая блокировка дверных замков при начале движения',
        'Электронный стояночный тормоз',
        'Система Эра-Глонасс',
      ],
    ),
    maintenanceCosts: MaintenanceCosts(
        id: '1',
        typeOfFuel: 'аи-95',
        fuelConsumptionUrbanCycle: 8.9,
        extraUrbanFuelConsumption: 6.2,
        combinedFuelConsumption: 7.2,
        travelDistance: 590,
        horsePower: 149,
        price: 3202964),
  );

  static Car mazdaCx5White = Car(
    id: '1',
    brand: 'Mazda',
    model: 'Cx-5',
    image: AppImages.mazdaCx5White,
    price: 3102964,
    bodyColor: 'Белый',
    productionYear: 2022,
    bodyType: 'Кроссовер',
    transmission: 'АКПП',
    engineType: 'Бензиновый',
    engineVolume: 2.0,
    equipment: Equipment(
      id: '1',
      title: 'Supreme 4WD',
      seatUpholstery: 'Alcantara',
      heatedSeats: 'Подогрев передних сидений',
      airbags: '7 подушек',
      onBoardComputer: 'Маршрутный компьютер',
      horsePower: 149,
      maxTorque: 208,
      typeOfFuel: 'Бензин',
      accelerationTime: 10.3,
      maxSpeed: 200,
      airConditioningSystem: 'Климат контроль (2 зоны)',
      multifunctionSteeringWheel: 'Управление аудиосистемой на рулевом колесе',
      fuelTankVolume: 58,
      centralLocking: 'Центральный замок с дистанционным управлением',
      trunkVolume: '442',
      driveUnit: 'Передний',
      additionalOptions: [
        'Автоматическая блокировка дверных замков при начале движения',
        'Электронный стояночный тормоз',
        'Система Эра-Глонасс',
      ],
    ),
    maintenanceCosts: MaintenanceCosts(
        id: '1',
        typeOfFuel: 'аи-95',
        fuelConsumptionUrbanCycle: 8.9,
        extraUrbanFuelConsumption: 6.2,
        combinedFuelConsumption: 7.2,
        travelDistance: 590,
        horsePower: 149,
        price: 3202964),
  );

  static Car mazdaCx5Black = Car(
    id: '1',
    brand: 'Mazda',
    model: 'Cx-5',
    image: AppImages.mazdaCx5Black,
    price: 3202964,
    bodyColor: 'Черный',
    productionYear: 2022,
    bodyType: 'Кроссовер',
    transmission: 'АКПП',
    engineType: 'Бензиновый',
    engineVolume: 2.0,
    equipment: Equipment(
      id: '1',
      title: 'Executive 4WD',
      seatUpholstery: 'Alcantara',
      heatedSeats: 'Подогрев передних сидений',
      airbags: '7 подушек',
      onBoardComputer: 'Маршрутный компьютер',
      horsePower: 149,
      maxTorque: 208,
      typeOfFuel: 'Бензин',
      accelerationTime: 10.3,
      maxSpeed: 200,
      airConditioningSystem: 'Климат контроль (2 зоны)',
      multifunctionSteeringWheel: 'Управление аудиосистемой на рулевом колесе',
      fuelTankVolume: 58,
      centralLocking: 'Центральный замок с дистанционным управлением',
      trunkVolume: '442',
      driveUnit: 'Передний',
      additionalOptions: [
        'Автоматическая блокировка дверных замков при начале движения',
        'Электронный стояночный тормоз',
        'Система Эра-Глонасс',
      ],
    ),
    maintenanceCosts: MaintenanceCosts(
        id: '1',
        typeOfFuel: 'аи-95',
        fuelConsumptionUrbanCycle: 8.9,
        extraUrbanFuelConsumption: 6.2,
        combinedFuelConsumption: 7.2,
        travelDistance: 590,
        horsePower: 149,
        price: 3202964),
  );
}
