import 'package:car_sale_app/app_values/app_images.dart';
import 'package:car_sale_app/model/Car.dart';
import 'package:car_sale_app/model/Equipment.dart';
import 'package:car_sale_app/model/maintenance_costs.dart';

abstract class MitsubishiModel {
  static Car mitsubishiL200White = Car(
    id: '6',
    brand: 'Mitsibishi',
    model: 'L200',
    image: AppImages.mitsubishiL200White,
    price: 4179000,
    bodyColor: 'Белый',
    productionYear: 2021,
    bodyType: 'Пикап',
    transmission: 'МКПП',
    engineType: 'Дизельный',
    engineVolume: 2.4,
    equipment: Equipment(
      id: '6',
      title: 'Diesel NP 2.4 DC Invite MT',
      seatUpholstery: 'Marathon',
      heatedSeats: 'Подогрев передних сидений',
      airbags: '6 подушек',
      onBoardComputer: 'Бортовой компьютер',
      horsePower: 154,
      maxTorque: 380,
      typeOfFuel: 'Дизельный',
      accelerationTime: 14.6,
      maxSpeed: 173,
      airConditioningSystem: 'Климат контроль',
      multifunctionSteeringWheel: 'Многофункциональный кожаный руль',
      fuelTankVolume: 75,
      centralLocking: 'Центральный замок',
      trunkVolume: '475',
      driveUnit: 'Полный',
      additionalOptions: [
        'Многорежимная трансмиссия EASY-SELECT 4WD',
        'Дистанционное управление лючком топливного бака',
        'Розетка электропитания 12B',
        'Система Эра-Глонасс',
      ],
    ),
    maintenanceCosts: MaintenanceCosts(
      id: '6',
      typeOfFuel: '-',
      fuelConsumptionUrbanCycle: 9,
      extraUrbanFuelConsumption: 7,
      combinedFuelConsumption: 7.7,
      travelDistance: 990,
      horsePower: 154,
      price: 4179000,
    ),
  );

  static Car mitsubishiL200Grey = Car(
    id: '6',
    brand: 'Mitsibishi',
    model: 'L200',
    image: AppImages.mitsubishiL200Grey,
    price: 4496050,
    bodyColor: 'Серый',
    productionYear: 2021,
    bodyType: 'Пикап',
    transmission: 'МКПП',
    engineType: 'Дизельный',
    engineVolume: 2.4,
    equipment: Equipment(
      id: '6',
      title: 'Diesel NP 2.4 DC Invite MT',
      seatUpholstery: 'Marathon',
      heatedSeats: 'Подогрев передних сидений',
      airbags: '6 подушек',
      onBoardComputer: 'Бортовой компьютер',
      horsePower: 154,
      maxTorque: 380,
      typeOfFuel: 'Дизельный',
      accelerationTime: 14.6,
      maxSpeed: 173,
      airConditioningSystem: 'Климат контроль',
      multifunctionSteeringWheel: 'Многофункциональный кожаный руль',
      fuelTankVolume: 75,
      centralLocking: 'Центральный замок',
      trunkVolume: '475',
      driveUnit: 'Полный',
      additionalOptions: [
        'Многорежимная трансмиссия EASY-SELECT 4WD',
        'Дистанционное управление лючком топливного бака',
        'Розетка электропитания 12B',
        'Система Эра-Глонасс',
      ],
    ),
    maintenanceCosts: MaintenanceCosts(
      id: '6',
      typeOfFuel: '-',
      fuelConsumptionUrbanCycle: 9,
      extraUrbanFuelConsumption: 7,
      combinedFuelConsumption: 7.7,
      travelDistance: 990,
      horsePower: 154,
      price: 4496050,
    ),
  );

  static Car mitsubishiL200Silver = Car(
    id: '6',
    brand: 'Mitsibishi',
    model: 'L200',
    image: AppImages.mitsubishiL200Silver,
    price: 4440000,
    bodyColor: 'Серебристый',
    productionYear: 2021,
    bodyType: 'Пикап',
    transmission: 'МКПП',
    engineType: 'Дизельный',
    engineVolume: 2.4,
    equipment: Equipment(
      id: '6',
      title: 'Diesel NP 2.4 DC Invite+ MT',
      seatUpholstery: 'Marathon',
      heatedSeats: 'Подогрев передних сидений',
      airbags: '6 подушек',
      onBoardComputer: 'Бортовой компьютер',
      horsePower: 154,
      maxTorque: 380,
      typeOfFuel: 'Дизельный',
      accelerationTime: 14.6,
      maxSpeed: 173,
      airConditioningSystem: 'Климат контроль',
      multifunctionSteeringWheel: 'Многофункциональный кожаный руль',
      fuelTankVolume: 75,
      centralLocking: 'Центральный замок',
      trunkVolume: '475',
      driveUnit: 'Полный',
      additionalOptions: [
        'Многорежимная трансмиссия EASY-SELECT 4WD',
        'Дистанционное управление лючком топливного бака',
        'Розетка электропитания 12B',
        'Система Эра-Глонасс',
      ],
    ),
    maintenanceCosts: MaintenanceCosts(
      id: '6',
      typeOfFuel: '-',
      fuelConsumptionUrbanCycle: 9,
      extraUrbanFuelConsumption: 7,
      combinedFuelConsumption: 7.7,
      travelDistance: 990,
      horsePower: 154,
      price: 4440000,
    ),
  );
}
